CREATE DATABASE BIBLIOTECA ON
PRIMARY (
 NAME = N'BIBLIOTECA',
 FILENAME = N'/var/opt/mssql/data/BIBLIOTECA.mdf',
 SIZE = 50MB ,
 FILEGROWTH = 10240KB
) LOG ON (
 NAME = N'BIBLIOTECA_log',
 FILENAME = N'/var/opt/mssql/data/BIBLIOTECA_log.ldf',
 SIZE = 10MB ,
 FILEGROWTH = 5MB
)
GO
